# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mosoo < Formula
  desc "Generated CLI for Mosoo integrators"
  homepage "https://github.com/langgenius/mosoo-connector"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/langgenius/mosoo-connector/releases/download/v0.1.1/mosoo-darwin-amd64.tar.gz"
      sha256 "5994298a0aa0db3163b60904e6d1cfc0bc25253f1d18bc86b9ede3420de5aff5"

      define_method(:install) do
        bin.install "mosoo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/langgenius/mosoo-connector/releases/download/v0.1.1/mosoo-darwin-arm64.tar.gz"
      sha256 "07e0703446930e28702b2b3fe57742ab060d12182599f578aa5c2d8a9271be1c"

      define_method(:install) do
        bin.install "mosoo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/langgenius/mosoo-connector/releases/download/v0.1.1/mosoo-linux-amd64.tar.gz"
      sha256 "55b94ae3709fd3df0974ca000b7ddf5f05cdaabc6e43b043da5fa46d0ade2f0c"
      define_method(:install) do
        bin.install "mosoo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/langgenius/mosoo-connector/releases/download/v0.1.1/mosoo-linux-arm64.tar.gz"
      sha256 "297abd5654563cfd8fa3693f35ed5fbd8353f2370001c974787671c39c7e880a"
      define_method(:install) do
        bin.install "mosoo"
      end
    end
  end

  test do
    assert_match "mosoo v0.1.1", shell_output("#{bin}/mosoo --version")
    system "#{bin}/mosoo", "commands", "--json"
  end
end
